### PR TITLE
fix: Compilation issue in armv7

### PR DESCRIPTION
**Pull request by DemonInTheCloset**
- Tested in a Raspberry Pi 4 running Arch Linux on ARM, all Cargo Tests pass

### CODE REVIEW

**Comment by grtcdr** [comment]
What exactly is the compilation issue?

**Comment by DemonInTheCloset** [comment]
```rust
let disk_size = stats.f_blocks * stats.f_bsize as u64;
```

On x86_64 stats.f_block is a `u64`, while on AArch64 it's a `u32`

**Comment by DemonInTheCloset** [comment]
Sorry, my mistake, it's not AArch64 but armv7 `stable-armv7-unknown-linux-gnueabihf`

**Comment by grtcdr** [comment]
Well, casting in this case is not very optimal, we should perhaps conditionally handle these differences with the `cfg!` macro.

**Comment by DemonInTheCloset** [comment]
A quick godbolt example should help: `https://godbolt.org/z/9h4dj3q9W`

Casting to `u64` in the current impl doesn't affect the asm output at all, while casting to `u64` in the armv7 impl adds 3 instructions, I'm not used to armv7 assembly so I can't be sure but casting to `u32` seems to allow the operation to be done in 1 instruction instead of 4 (although the 3 extra instructions should be really cheap).

In this case using a `cfg` directive should help, I'll rework the pull request.

**Comment by grtcdr** [comment]
Thanks for the detailed explanation.

> In this case using a cfg directive should help, I'll rework the pull request.

Great, I'll be watching over this PR.

**Comment by DemonInTheCloset** [comment]
It seems the `libc::statfs` internally uses `usize` and `isize` (so `size_t` and `ssize_t`), and therefore the types change on a 32-bit architecture like armv7.

**Comment by grtcdr** [comment]
Looks good to me, although I wonder if `target_pointer_width` could cause any issues in the future, I've never used and wasn't aware of its existence before.

**Comment by DemonInTheCloset** [comment]
I couldn't find any other `cfg` attribute which would work (ARM is not the problem but the 32-bit CPU).

It might cause issues when adding another target, which, for some reason, has a strange `statfs`, but in that case I would wager that it should be treated as the exception.

In theory we could also handle 16-bit targets https://doc.rust-lang.org/reference/conditional-compilation.html#target_pointer_width.

**Comment by grtcdr** [comment]
> I couldn't find any other cfg attribute which  > would work (ARM is not the problem but the 32-bit CPU).

I see, I have no problem with this approach :)

> It might cause issues when adding another > target, which, for some reason, has a strange statfs, but in that case I would argue > that it should be treated as the exception, not the rule.

I fully agree, and thank you for working on this!

**Pull request merged**
