### PR TITLE
Add FreeBSD uptime detection

### PR DESCRIPTION
**Pull request by Gobidev**
This PR adds uptime detection on FreeBSD by spawning a `sysctl` system command. This is sadly pretty much the fastest option on FreeBSD, as getting the uptime requires a syscall and cannot be read directly from /proc.

### CODE REVIEW

**Comment by CarterLi** [comment]
So starting a process is faster than emitting a syscall.

What?

**Comment by Gobidev** [comment]
@CarterLi you're right, I somehow did not think of making the syscall directly😅
I will look into how that could be done

**Comment by Gobidev** [comment]
It looks like the [sysinfo](https://crates.io/crates/sysinfo) crate already has such an implementation already that uses  the [libc](https://crates.io/crates/libc) crate to interact with `sysctl` directly. The question is if the plan for this project is to have its own implementation or not. If not, we could just add `sysinfo` as a FreeBSD dependency and use that.

**Comment by Gobidev** [comment]
Ok, in that case I will work on a proper implementation without spawning a process, closing this for now.

**Pull request closed without merging**
