### PR TITLE
Add android support

### PR DESCRIPTION
**Pull request by uttarayan21**
Android support 
packages ( apps ) counts by
`pm list packages`
battery level from 
`/sys/class/power_supply/battery/`
product readout from 
`getprop ro.product.model` / `getprop ro.product.brand` 

libc::loadavg is not implemented in bionic libc before api 29 (android 10).
I will try to get this to work [libc/bionic/getloadavg.cpp](https://android.googlesource.com/platform/bionic/+/refs/heads/master/libc/bionic/getloadavg.cpp) of before sdk 29.

Screenshot
termux-macchina

### CODE REVIEW

**Comment by grtcdr** [comment]
Oh I'm glad this is back, I closed a very old PR that wanted to add android support, but this was back when macchina was responsible for fetching and libmacchina didn't exist.

I'll delay Cobalt's release and wait for you to finish this up.

Maybe the next version can have Android support.

**Comment by uttarayan21** [comment]
I'm trying to build this such that it can run irrespective of termux. 
But currently most of the testing I did was inside termux.

**Comment by grtcdr** [comment]
> I'm trying to build this such that it can run irrespective of termux.
> But currently most of the testing I did was inside termux.

How do you run a CLI program on Android without Termux?

**Comment by uttarayan21** [comment]
You can run it via adb but I don't think most people will try that.
Other than that you can try to install it as a magisk module and then try it from any terminal emulator on android.
But you can't run it off of the sdcard/internal storage since they are mounted as noexec in android.

**Comment by grtcdr** [comment]
> You can run it via adb but I don't think most people will try that.
> Other than that you can try to install it as a magisk module and then try it from any terminal emulator on android.
> But you can't run it off of the sdcard/internal storage since they are mounted as noexec in android.

Dang it, it's so locked down.

If you are going to target Termux, you can add a fallback command to count_dpkg() that runs dpkg -l | wc -l, because currently it fetches the installed packages from a very specific directory that would only be accessible on Linux.

**Comment by uttarayan21** [comment]
`getprop` is an android only thing.

It reads properties for the os from /system/build.prop
But it is not readable by a normal user without root access.

**Comment by uttarayan21** [comment]
I also tried using the [android-properties](https://crates.io/crates/android-properties) crate but it uses `__system_property_read_callback` which is only available in libc after sdk 21. But I currently don't know how to compile against a specific sdk version. So it doesn't compile.

**Comment by grtcdr** [comment]
> I also tried using the [android-properties](https://crates.io/crates/android-properties) crate but it uses `__system_property_read_callback` which is only available in libc after sdk 21.
> 
> But I currently don't know how to compile against a specific sdk version. So it doesn't compile.

Neither do I :/

**Comment by uttarayan21** [comment]
Yeah android is not particularly well suited for cli applications.

Also should I include all apps in android package readout or just user installed apps ?

**Comment by grtcdr** [comment]
> Yeah android is not particularly well suited for cli applications.
> 
> Also should I include all apps in android package readout or just user installed apps ?

If it's possible include them system-wide + current user's installed packages, so the user can get an idea of that number.

**Comment by grtcdr** [comment]
Did you replace the Linux ASCII art with the Android one or did you add distro-specific ASCII art?

**Comment by uttarayan21** [comment]
> Did you replace the Linux ASCII art with the Android one or did you add distro-specific ASCII art?

I added a new target_os = android target

**Comment by grtcdr** [comment]
> Is that ok ?

Print the total without mentioning how many are per-user, then you're good to go :)

**Comment by uttarayan21** [comment]
Most of the stuff is done but I can't seem to implement the loadavg.

I tried the [sysinfo](https://crates.io/crates/sysinfo) crate which reports CPU usage as zero.
I tried parsing `/proc/loadavg` which has 0.0 in all three fields for the load and cannot even be read on OEM stock roms / custom roms which enforce SELinux.
I tried parsing `uptime` command output but that also returns loadavg as zero.
I also tired the libc::loadavg but the bionic doesn't expose the function.
I haven't tried `/proc/stat` but I believe that will also not be readable with SELinux enabled.

**Comment by grtcdr** [comment]
> Most of the stuff is done but I can't seem to implement the loadavg.
> 
> I tried the [sysinfo](https://crates.io/crates/sysinfo) crate which reports CPU usage as zero.
> I tried parsing `/proc/loadavg` which has 0.0 in all three fields for the load and cannot even be read on OEM stock roms / custom roms which enforce SELinux.
> I tried parsing `uptime` command output but that also returns loadavg as zero.
> I also tired the libc::loadavg but the bionic doesn't expose the function.
> I haven't tried `/proc/stat` but I believe that will also not be readable with SELinux enabled.
> 
> I might try to make an extern c function that will take input from the sysinfo function from [<sys/sysinfo.h>](https://man7.org/linux/man-pages/man2/sysinfo.2.html) to get the load, but I'm not sure even if that will work.

I'm guessing Google doesn't provide direct access to this kind of information, just fail the readout until a solution comes up.

**Comment by grtcdr** [comment]
I'll review it in a little bit 👀

**Comment by uttarayan21** [comment]
I'll make a macchina pull request soon with the ascii art and stuff.

**Comment by grtcdr** [comment]
> I'll make a macchina pull request soon with the ascii art and stuff.
> 
> BTW I also added a function `count_lines` in extra.rs to use instead of `wc -l`

Awesome, less commands, less piping into them :+1:

**Comment by grtcdr** [comment]
After we merge this, you should take a look at #14, I hope this statistic is available on Android.

**Comment by uttarayan21** [comment]
> After we merge this, you should take a look at #14, I hope that statistic is available on Android.

Yeah It's pretty much same as linux but instead of `/sys/class/power_supply/BAT0/` it has `/sys/class/power_supply/battery`
and instead of `energy_full` and `energy_full_design` it has `charge_full` and `charge_full_design`

**Comment by grtcdr** [comment]
> > After we merge this, you should take a look at #14, I hope that statistic is available on Android.
> 
> Yeah It's pretty much same as linux but instead of `/sys/class/power_supply/BAT0/` it has `/sys/class/power_supply/battery`
> and instead of `energy_full` and `energy_full_design` it has `charge_full` and `charge_full_design`

Great, I'm glad it isn't that much different.

**Comment by grtcdr** [comment]
count_lines() can output incorrect line count in certain cases; let's assume that we have the following buffer than contains:
```
package_1\n
package_2\n
package_3
```
count_lines() is going to return 2 here, when we have three lines in the buffer.

The last line **might** also contain a newline, but no line actually comes after it.

**Comment by uttarayan21** [comment]
Okay the count_lines does have a mistake but I don't think the second mistake is valid.
something like 
```
a\n
b\n
c\n
```
is basically
```
a
b
c

```
and wc -l on that will result in 4 lines instead of 3
So I think adding 1 to the count_lines should suffice.

**Comment by grtcdr** [comment]
wc does have its shortcomings too, we just need a solution that takes into account these edge cases.

**Comment by uttarayan21** [comment]
Yeah I just made the change.

**Comment by grtcdr** [comment]
> Yeah I just made the change.

Great, I think we're good :partying_face:

**Comment by uttarayan21** [comment]
Okay I also added a trim() before pop_newline so that any blank newlines are also removed.

**Comment by grtcdr** [comment]
> Okay I also added a trim() before pop_newline so that any blank newlines are also removed.

Great idea :)

We don't need build_android() though.

**Comment by uttarayan21** [comment]
Oh yeah I forgot to remove it.

And also I added the generic ToString to the pop_newline function.

**Comment by grtcdr** [comment]
Great work :rocket:

**Review by grtcdr — APPROVED** [review]

**Comment by uttarayan21** [comment]
But I already did [that](https://github.com/Macchina-CLI/libmacchina/pull/21/files/ce3c7a533986d4d039a709b07b9220b6937868c8#diff-1301546b748dfb41ab820f73326113ab9f458c7656e02a2ded9670d732cf036dR287)

**Comment by grtcdr** [comment]
> But I already did [that](https://github.com/Macchina-CLI/libmacchina/pull/21/files/ce3c7a533986d4d039a709b07b9220b6937868c8#diff-1301546b748dfb41ab820f73326113ab9f458c7656e02a2ded9670d732cf036dR287)

I need a new set of glasses lol, sorry about that..

**Comment by uttarayan21** [comment]
> I need a new set of glasses lol, sorry about that.

Haha no problem but due to that I caught the mistake in the comments.

**Comment by grtcdr** [comment]
> > I need a new set of glasses lol, sorry about that.
> 
> Haha no problem but due to that I caught the mistake in the comments.

I have a question, is pm Android's package manager?

If so, I think it's better to rename the PackageManager::Android to_string return value to "pm", to make it apparent to the user which package manager that is.

**Comment by uttarayan21** [comment]
Yes pm is the PackageManager built into all android devices you can't remove / change it.

**Comment by grtcdr** [comment]
> Yes pm is the PackageManager built into all android devices you can't remove / change it.

Okay, thanks for clearing that up!

How is performance by the way?

**Comment by uttarayan21** [comment]
It is around 150ms as measured by `time`.
But neofetch is around 700ms so that's a lot better.

**Review by grtcdr — APPROVED** [review]

**Comment by uttarayan21** [comment]
Here is a benchmark with hyperfine
bench

**Comment by grtcdr** [comment]
> It is around 150ms as measured by `time`.

Not bad, we can still work to improve this before the next release.

**Comment by uttarayan21** [comment]
Yeah I believe we'll get the most improvement from removing the `getprop` calls via shell and instead call it from a library.

I'll look into it tomorrow.

**Comment by grtcdr** [comment]
> Yeah I believe we'll get the most improvement from removing the `getprop` calls via shell and instead call it from a library.
> 
> I'll look into it tomorrow.

Yeah I thought so too, I'll merge for now :)

**Pull request merged**
