### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by FantasyTeddy**
* Format files according to `cargo fmt`
* Fix errors reported by clippy

### CODE REVIEW

**Comment by grtcdr** [comment]
Perfect! Just in time for v6 :smile: 

Thank you Teddy :heart:

**Comment by FantasyTeddy** [comment]
Glad I can help 😄 

Should we maybe adjust the workflows to fail if either one of these checks fails?

**Comment by grtcdr** [comment]
> Should we maybe adjust the workflows to fail if either one of these checks fails?

Agreed, but I believe we should only fail if clippy throws a warning.

**Comment by FantasyTeddy** [comment]
> Agreed, but I believe we should only fail if clippy throws a warning.

Okay, can you elaborate why you don't want to fail for `cargo fmt`?

**Comment by grtcdr** [comment]
I don't think it's necessary, what are your thoughts?

**Comment by FantasyTeddy** [comment]
I like a well formatted codebase and the Rust formatter does an excellent job of keeping it consistent.
Therefore I would turn it on as well and prevent cleanup commits like this one 😉

**Comment by grtcdr** [comment]
Seems reasonable, I'll get that going ASAP :)

**Pull request merged**
