### PR TITLE
Add openwrt support.

### PR DESCRIPTION
**Pull request by uttarayan21**
I'm trying to add support for openwrt.
I've already added opkg.
openwrt

It is working but a few fields are missing, I'll try to work them out.

### CODE REVIEW

**Comment by grtcdr** [comment]
Very cool! I'm always around if you need any help, or have any questions.

**Comment by uttarayan21** [comment]
Thanks.
So I've collected a bit of info.
CPU model lookup fails since 
```bash
root@OpenWrt:~# cat /proc/cpuinfo  | grep model
cpu model               : MIPS 1004Kc V2.15
cpu model               : MIPS 1004Kc V2.15
cpu model               : MIPS 1004Kc V2.15
cpu model               : MIPS 1004Kc V2.15
```
There is no model name only the type of cpu so I'm thinking to display `MIPS 1004Kc V2.15` instead of empty space.

Terminal, DesktopEnvironment, WindowManger fails since it has no gui.

The machine readout fails since there is no `/sys/class/dmi`.

However most of this is displayed in the luci web-ui.
luci

So I am going to try to make the `Machine` readout work and try to display correct info in the `CPU` readout.

**Comment by uttarayan21** [comment]
More information.

`Machine` readout can be obtained by 
```bash
root@OpenWrt:/proc# cat cpuinfo  | grep machine
machine                 : Xiaomi Mi Router 3G
```
In cpu readout for linux 
```rust
  if l.starts_with("model name") {
      return l ‣String
          .replace("model name", "") ‣String
          .replace(":", "") ‣String
          .trim() ‣&str
          .to_string();
  }
```
It is checked if the line starts with `"model name"`,
but in OpenWrt (`Linux OpenWrt 4.14.221 mips`)
in the `/proc/cpuinfo` file the cpu model start with  `"cpu model"`.
This probably occurs due to the older kernel.

So while the target os is still linux this makes parsing things a bit confusing.

**Comment by uttarayan21** [comment]
Hey @grtcdr I have made the changes and it runs fine but the code isn't as clean as I'd like.
Can you check it ?

**Comment by grtcdr** [comment]
A more optimal approach is to have a separate directory and mod.rs implementation, but this depends on one thing:
the cpu architecture of OpenWrt systems, is its `target_arch` value `mips` or `linux`.

If its the former, than we can go ahead and add a separate directory for OpenWrt and implement the `Readout` types to target OpenWrt specifically.

If its the latter, then I'll refactor what I can, if there is refactoring work to do.

**Comment by uttarayan21** [comment]
This could but work but Openwrt systems can be of many architectures
And if someone were to run this on an non openwrt mips machine this would break it.
Here is a list of architectures supported by openwrt https://openwrt.org/packages/architectures.

**Comment by grtcdr** [comment]
> Here is a list of architectures supported by openwrt https://openwrt.org/packages/architectures.
That's a pretty big list, let me think of something before we move forward with this approach.

**Comment by uttarayan21** [comment]
We could have something like a feature flag or environment variable at compile time that would tell cargo to build for openwrt.

I have no clue about how the `build.rs` build scripts work but I'll try to look into it.

**Comment by grtcdr** [comment]
> We could have something like a feature flag or environment variable at compile time that would tell cargo to build for openwrt.
Good idea :+1:

**Comment by uttarayan21** [comment]
> @uttarayan21 We can run a certain feature depending on the output of a modified version of `GeneralReadout::distribution()`, because that function can return both **NAME** and **VERSION**, we'll also need a new `build_linux()` in `build.rs` that contains something like this:
> 
So , like, we add a check to linux `GeneralReadout::distribution()`

But I think the compile time feature flag will be better since for openwrt we probably will be cross-compiling and the /etc/os-release will not coresspond to the target machine.

> ```
> println!("cargo:rustc-cfg=feature=openwrt");
> ```

So if am understanding it correctly we just add a new feature to `libmacchina` called openwrt and then add the above to the build.rs in `macchina` when the --features=openwrt is called ?.

**Comment by uttarayan21** [comment]
Also I tried doing this.
```rust
    if #[cfg(target_os = "linux")] {
            if #[cfg(features = "openwrt")] {
                mod openwrt;
                pub type BatteryReadout = openwrt::OpenwrtBatteryReadout;
                pub type KernelReadout = openwrt::OpenwrtKernelReadout;
                pub type MemoryReadout = openwrt::OpenwrtMemoryReadout;
                pub type GeneralReadout = openwrt::OpenwrtGeneralReadout;
                pub type ProductReadout = openwrt::OpenwrtProductReadout;
                pub type PackageReadout = openwrt::OpenwrtPackageReadout;
            } else {
                mod linux;
                pub type BatteryReadout = linux::LinuxBatteryReadout;
                pub type KernelReadout = linux::LinuxKernelReadout;
                pub type MemoryReadout = linux::LinuxMemoryReadout;
                pub type GeneralReadout = linux::LinuxGeneralReadout;
                pub type ProductReadout = linux::LinuxProductReadout;
                pub type PackageReadout = linux::LinuxPackageReadout;
            }
    }
```
but it seems that I cannot use cfg_if with features atleast not like I'm currently trying to do.

**Comment by grtcdr** [comment]
Can you test the `openwrt-testing` branch I just created?
I don't want to ruin your progress with my experiments so I made it its own branch.

**Comment by uttarayan21** [comment]
> `#[cfg(all(target_os = "linux", feature = "openwrt"))]`
Ah I see so that's how you do it.

Yes I just pull upstream/openwrt-testing to my local branch I'll test it out after fixing some merge conficts.

**Comment by grtcdr** [comment]
> > `#[cfg(all(target_os = "linux", feature = "openwrt"))]`
> 
> Ah I see so that's how you do it.
> 
> Yes I just pull upstream/openwrt-testing to my local branch I'll test it out after fixing some merge conficts.

Yeah there's only one issue, the first if statement, the one for Linux:
```
if #[cfg(target_os = "linux")]
```
should actually check for target_os and also check if the feature is disabled, so `not(feature = "openwrt")`

**Comment by uttarayan21** [comment]
I just tried you `upsteam/openwrt-testing` branch, the conditional compilation works fine now.
Now I just need to implement the things that work in OpenWrt.

**Comment by grtcdr** [comment]
> I just tried you `upsteam/openwrt-testing` branch, the conditional compilation works fine now.
> Now I just need to implement the things that work in OpenWrt.

Awesome! I'm looking for a way to use not(feature = "openwrt") and target_os = "linux" in the same cfg attribute, I seem to be doing something wrong...

**Comment by uttarayan21** [comment]
> Awesome! I'm looking for a way to use not(feature = "openwrt") and target_os = "linux" in the same cfg attribute, I seem to be doing something wrong...

This seems to work for me 
```rust
 #[cfg(all(target_os = "linux", not(feature = "openwrt")))]
```

**Comment by grtcdr** [comment]
> > Awesome! I'm looking for a way to use not(feature = "openwrt") and target_os = "linux" in the same cfg attribute, I seem to be doing something wrong...
> 
> This seems to work for me
> 
> ```rust
>  #[cfg(all(target_os = "linux", not(feature = "openwrt")))]
> ```

Yeah, I couldn't figure that one out so I asked for help over at Rust's official discord channel.

**Comment by grtcdr** [comment]
@uttarayan21 Since OpenWrt is Linux at the core, I imagine `opkg` might have a directory that contains the installed programs, sort of like `pacman` stores its packages in _/var/lib/pacman/local_

Not all package managers do it the same, but try looking for a directory similar to this, maybe we can extract installed packages by reading the entries of that directory (if it exists).

**Comment by uttarayan21** [comment]
Yes I actually tried doing that but openwrt is a little different than a normal linux system.
The root is a squashfs filesystem mounted read-only and then an overlay filesystem is mounted on top of it which contains all the changes made to the root filesysem.
```bash
root@OpenWrt:/# mount
/dev/root on /rom type squashfs (ro,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,noatime)
/dev/ubi0_1 on /overlay type ubifs (rw,noatime,ubi=0,vol=1)
overlayfs:/overlay on / type overlay (rw,noatime,lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work)
tmpfs on /dev type tmpfs (rw,nosuid,relatime,size=512k,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,mode=600,ptmxmode=000)
debugfs on /sys/kernel/debug type debugfs (rw,noatime)
```

There is however a file in the filesystem which had the info about opkg packages in it whose path I currently don't remember.
```bash
root@OpenWrt:/# find -name '*opkg*'
./bin/opkg
./etc/config/adblock-opkg
./etc/opkg
./etc/opkg.conf
./lib/upgrade/keep.d/opkg
./overlay/upper/etc/opkg
./overlay/upper/etc/config/adblock-opkg
./overlay/upper/usr/lib/opkg
./rom/bin/opkg
./rom/etc/opkg
./rom/etc/opkg.conf
./rom/lib/upgrade/keep.d/opkg
./rom/usr/lib/lua/luci/controller/opkg.lua
./rom/usr/lib/lua/luci/view/opkg.htm
./rom/usr/lib/opkg
./rom/usr/lib/opkg/info/luci-app-opkg.control
./rom/usr/lib/opkg/info/luci-app-opkg.list
./rom/usr/lib/opkg/info/luci-app-opkg.prerm
./rom/usr/lib/opkg/info/opkg.conffiles
./rom/usr/lib/opkg/info/opkg.control
./rom/usr/lib/opkg/info/opkg.list
./rom/usr/lib/opkg/info/opkg.prerm
./rom/usr/sbin/opkg-key
./rom/www/luci-static/resources/view/opkg.js
./tmp/usr/lib/opkg
./tmp/opkg-lists
./usr/lib/lua/luci/controller/opkg.lua
./usr/lib/lua/luci/view/opkg.htm
./usr/lib/opkg
./usr/lib/opkg/info/luci-app-opkg.control
./usr/lib/opkg/info/luci-app-opkg.list
./usr/lib/opkg/info/luci-app-opkg.prerm
./usr/lib/opkg/info/opkg.conffiles
./usr/lib/opkg/info/opkg.control
./usr/lib/opkg/info/opkg.list
./usr/lib/opkg/info/opkg.prerm
./usr/sbin/opkg-key
./www/luci-static/resources/view/opkg.js
```
This is a list of all files contaning the word opkg

**Comment by uttarayan21** [comment]
Alright so I fount the file which contains all the list of pakcage names.
I did
```bash
cat /usr/lib/opkg/status | grep -c 'Package'
```
So we can do something like in rust.
```rust
if line.starts_with("Package:") {
    count += 1
}
```

**Comment by grtcdr** [comment]
> Alright so I fount the file which contains all the list of pakcage names.
> I did
> 
> ```shell
> cat /usr/lib/opkg/status | grep -c 'Package'
> ```
> 
> So we can do something like in rust.
> 
> ```rust
> if line.starts_with("Package:") {
>     count += 1
> }
> ```

Great, you found it!

**Comment by uttarayan21** [comment]
Hey @grtcdr I think its done for the most part. Need to do a litte bit more testing. Can you take a look ?

Also the distribution function in `build.rs` is useless since it uses the `os_release` which is in the current machine which is definetly not going to be OpenWrt. So I'm removing it.

To compile I'm using [cross](https://github.com/rust-embedded/cross)

```bash
cross build --target mipsel-unknown-linux-musl --features=openwrt --release
```

**Comment by uttarayan21** [comment]
Also need to do this to macchina's `Cargo.toml`
```diff
diff --git a/Cargo.toml b/Cargo.toml
index 6e02c4f..d59284a 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -29,3 +29,6 @@ lazy_static = "1.4.0"

 [target.'cfg(not(target_env = "msvc"))'.dependencies]
 jemallocator = "0.3.2"
+
+[features]
+openwrt = ["libmacchina/openwrt"]
```
Then compile with
> `cross build --target mipsel-unknown-linux-musl --features=openwrt --release`

**Comment by uttarayan21** [comment]
Current sreenshot running my openwrt router.
macchina

**Comment by grtcdr** [comment]
> Current sreenshot running my openwrt router.
> macchina

Nice :)

I checked out the changes, and everything looks good!

**Comment by grtcdr** [comment]
> ```
> +openwrt = ["libmacchina/openwrt"]
> ```

Shouldn't that be "src/openwrt" though?

**Comment by uttarayan21** [comment]
That is actually the syntax that I fount in the rust books.
For the feature `openwrt` of `macchina` compile feature `openwrt` of `libmacchina`

**Comment by grtcdr** [comment]
> That is actually the syntax that I fount in the rust books.
> For the feature `openwrt` of `macchina` compile feature `openwrt` of `libmacchina`.
> 
> Probably also sould bump the version.

**Comment by grtcdr** [comment]
Sorry for the misclick!
Yeah, go ahead and bump up the version number :+1:

**Comment by uttarayan21** [comment]
So should I put it 0.1.10 or 0.2.0

**Comment by grtcdr** [comment]
> So should I put it 0.1.10 or 0.2.0

0.2.0

**Comment by grtcdr** [comment]
@uttarayan21 Great work, and thanks for your contribution, I can attribute your contributions in `Contributors` section of Macchina's GitHub repository if you'd like.

**Comment by uttarayan21** [comment]
Haha sure.
Thanks for your project too.

**Comment by grtcdr** [comment]
@uttarayan21 Could you please add a section for OpenWrt in Macchina's [installation wiki page](https://github.com/Macchina-CLI/macchina/wiki/Installation)?

**Comment by uttarayan21** [comment]
Oh yeah sure I'll do that.

**Comment by grtcdr** [comment]
> Oh yeah sure I'll do that.

Thank you so much :smile:

**Comment by uttarayan21** [comment]
I have added it to the installation part in the wiki.

**Pull request merged**
