### PR TITLE
Improve CI workflow

### PR DESCRIPTION
**Pull request by FantasyTeddy**
These are the same changes already applied to `macchina`: Macchina-CLI/macchina#311 & Macchina-CLI/macchina#313
- Replacement of `actions-rs` with [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain) and explicit calls to the respective `cargo`/`cross` commands.
- Extracting the `cargo fmt` and `cargo clippy` steps into their own jobs.
- Fail `clippy` on warnings (required some minor code changes).

### CODE REVIEW

**Comment by grtcdr** [comment]
Hey there, thank you so much for the pull request. :)

Regarding the job approach, to me it seems inefficient splitting what could remain a simple step into two jobs that duplicate two steps: checking out the repository and initializing the toolchain. In total, this results in three separate checkouts and toolchain installations.

**Comment by FantasyTeddy** [comment]
Okay, I see your point. I merged the two jobs into one.

**Review by Gobidev — APPROVED** [review]
Looks good to me :+1:

**Comment by grtcdr** [comment]
Thank you @FantasyTeddy!

**Pull request merged**
