### PR TITLE
Allow disk_space function to accept a path argument

### PR DESCRIPTION
**Pull request by Rolv-Apneseth**
In relation to #155 

I can't test if it works as intended for other OS's, but let me know if I missed anything here.

### CODE REVIEW

**Comment by Rolv-Apneseth** [comment]
Ah sure yeah my bad, didn't think about that

**Comment by Rolv-Apneseth** [comment]
> Yes, although I'm gonna hold off on any releases because we've been recently breaking things back to back, in a short period of time.

Alright that's fine. Will the `libmacchina` crate still be updated so that I can make the changes to `macchina` or will I hold of on that for now?

**Comment by Rolv-Apneseth** [comment]
Hey, just checking, anything else you wanted from this?

**Comment by grtcdr** [comment]
Hi,

> anything else you wanted from this?

Small nitpick: `path` should be of type `Path` and we should check if the `path` exists before continuing.

**Comment by Rolv-Apneseth** [comment]
Yeah I was wondering about that, I had decided to just keep it as it was in the `shared::disk_space` function but yeah I can make that change. Should it return a `ReadoutError::Other`?

**Comment by grtcdr** [comment]
Could you make the same change to `shared::disk_space`?

> Should it return a ReadoutError::Other?

If the path is incorrect then `ReadoutError::Other` is indeed the most appropriate return value.

**Comment by Rolv-Apneseth** [comment]
Let me know if that works and if I missed anything, I was definitely iffy on the part with the `CString` as that's my first time seeing that. I got it working with my changes to `macchina` anyways so seems ok as far as I can tell.

**Comment by Rolv-Apneseth** [comment]
Lot of minor fixes there. Is there any way to have the linting or testing point out these errors locally? Also I just copied the code I implemented for the `shared` function to to the `netbsd` implementation, no idea if that works though.

**Comment by grtcdr** [comment]
Wonderful, thanks a lot!

CI will lint, build and test the code of every platform, though testing remains the weakest point of libmacchina.

**Pull request merged**
