### PR TITLE
Fix a lot of clippy warnings

### PR DESCRIPTION
**Pull request by uttarayan21**
Fixed a lot of clippy warnings.
Should not make any tangible performance improvements.
Certain iterators were collected then length was taken , those were changed to count length of the iterator directly.
But cannot benchmark because of issue [macchina/issue#67](https://github.com/Macchina-CLI/macchina/issues/67)

### CODE REVIEW

**Comment by grtcdr** [comment]
Thanks @uttarayan21 and very nice refactoring work!

I'll give it a go in a little bit :)

**Comment by uttarayan21** [comment]
Thanks.

Also it seems that my previous commits are also in this pull request. 
It might have gone away if deleted and re forked but I didn't know at that time.
So I think only the last commit is the one with changes.

**Comment by grtcdr** [comment]
> Thanks.
> 
> Also it seems that my previous commits are also in this pull request.
> It might have gone away if deleted and re forked but I didn't know at that time.
> So I think only the last commit is the one with changes.

That's alright, I've had this happen to me before, not a big deal though, since we can squash and merge :)

**Review by grtcdr — APPROVED** [review]
Looks good, let's merge :)

**Pull request merged**
