### PR TITLE
Improve CI

### PR DESCRIPTION
**Pull request by FantasyTeddy**
I'm trying to get the build pipeline to pass.
The following changes are made:
- Tests are only executed on supported platforms (not on NetBSD & FreeBSD)
- FreeBSD added as target

Currently the "Linux (aarch64-unknown-linux-gnu)" build job is still failing. What is the purpose of this configuration? Is this for OpenWrt?

### CODE REVIEW

**Comment by grtcdr** [comment]
Thanks for adding FreeBSD to the list, I tried doing this before and gave up.

As for the aarch64 target, that one's for OpenWrt, `which` fails for some reason but the openwrt module makes no use of `which` so we can avoid running it when the `openwrt` feature is enabled.

**Comment by FantasyTeddy** [comment]
Are you sure that the `aarch64-unknown-linux-gnu` build is actually building with the `openwrt` feature? If so, can you explain how this works?

**Comment by grtcdr** [comment]
At the moment, the `openwrt` feature isn't being enabled for aarch64, I'll look into how we can do that...

**Comment by FantasyTeddy** [comment]
I tried to add proper support for OpenWrt in the CI pipeline in my last 2 commits. What do you think?

**Comment by grtcdr** [comment]
Looks great!

**Comment by grtcdr** [comment]
Looks like we're good to merge, shall I?

**Comment by FantasyTeddy** [comment]
Sure, I think this will give us more confidence when refactoring things that affect multiple targets.

**Pull request merged**
