### PR TITLE
Mac: Add backlight readout

### PR DESCRIPTION
**Pull request by 123marvin123**
Adds the macOS backlight readout implementation. Works on my M1 Macbook.

### CODE REVIEW

**Review by grtcdr — APPROVED** [review]
Looks good! Thanks :)

But it seems your editor messed up the indentation on a few lines.

**Comment by 123marvin123** [comment]
> Looks good! Thanks :)
> 
> But it seems your editor messed up the indentation on a few lines.

Yes, something must have gone wrong with the formatting but I am not sure what the correct formatting would be?

**Comment by grtcdr** [comment]
I've fixed both :) It should build fine now.

**Comment by grtcdr** [comment]
I'll try to land this along with the lockfile issue I've been trying to address since yesterday.

**Pull request merged**
